name = "auto-reaction-bot"
main = "api/worker.js"
compatibility_date = "2024-06-02"

[vars]
BOT_TOKEN = "7516178180:AAHOZ6EdFOI02VnA0o66cvdVehA7CUJ0oqY"
BOT_USERNAME = "Meaanggbot"
EMOJI_LIST = "ğŸ‘â¤ğŸ”¥ğŸ¥°ğŸ‘ğŸ˜ğŸ‰ğŸ¤©ğŸ™ğŸ‘ŒğŸ•ŠğŸ˜ğŸ³â¤â€ğŸ”¥ğŸ’¯âš¡ğŸ†ğŸ¦„ğŸ‘»ğŸ«¦ğŸ†ğŸŒ½ğŸŒğŸŒˆğŸ‘…ğŸª¿"
RANDOM_LEVEL = "2"
RESTRICTED_CHATS = "1234,5678"
